import { httpAction } from "./_generated/server";
import { api } from "./_generated/api";

// Site configuration
const SITE_URL = process.env.SITE_URL || "https://hirenest.ai";
const SITE_NAME = process.env.SITE_NAME || "Hirenest AI";

// Generate llms.txt dynamically
export const llmsTxt = httpAction(async (ctx) => {
    try {
        // Fetch all published posts
        // Fetch all published posts using pagination
        let currentCursor: string | null = null;
        let allPublishedPosts: any[] = [];
        let isDone = false;

        // Fetch all posts in batches
        while (!isDone) {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const result: any = await ctx.runQuery(api.posts.getRSSPostsBatch, {
                cursor: currentCursor,
                numItems: 100,
                includeContent: false
            });
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const filtered = result.posts.filter((p: any) => p.published && !p.unlisted);
            allPublishedPosts.push(...filtered);
            currentCursor = result.continueCursor;
            isDone = result.isDone;

            // Safety limit of 5000 posts
            if (allPublishedPosts.length > 5000) break;
        }

        const posts = allPublishedPosts;

        console.log(`[llms.txt] Generating with ${posts.length} posts`);

        // Generate Available Content section
        let availableContent = "";
        if (posts.length > 0) {
            availableContent = "\n## Available Content\n\n";

            // Sort posts by date descending
            const sortedPosts = [...posts].sort(
                (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
            );

            for (const post of sortedPosts) {
                const postUrl = `${SITE_URL}/blog/${post.slug}`;
                const markdownUrl = `${SITE_URL}/raw/${post.slug}.md`;

                availableContent += `### [${post.title}](${postUrl})\n`;
                availableContent += `- **Type**: Post\n`;
                availableContent += `- **Date**: ${post.date}\n`;
                availableContent += `- **Markdown URL**: ${markdownUrl}\n`;
                if (post.description) {
                    availableContent += `- **Description**: ${post.description}\n`;
                }
                availableContent += "\n";
            }
        }

        // Generate the complete llms.txt content
        const content = `# ${SITE_NAME}

This file provides LLM-friendly access to the content on this website.

---
- **Site URL**: ${SITE_URL}
- **Format**: Append \`?llm=1\` to any post/page URL to get markdown
---
${availableContent}
---
*Generated by [LLM Ready](https://hirenest.ai) - Make your content AI-ready*
`;

        return new Response(content, {
            headers: {
                "Content-Type": "text/plain; charset=utf-8",
                "Cache-Control": "public, max-age=3600, s-maxage=7200",
            },
        });
    } catch (error) {
        console.error("[llms.txt] Error generating:", error);

        // Return a minimal fallback
        const fallback = `# ${SITE_NAME}

This file provides LLM-friendly access to the content on this website.

Error: Unable to load content at this time. Please try again later.

---
*Last updated: ${new Date().toISOString()}*
`;

        return new Response(fallback, {
            status: 500,
            headers: {
                "Content-Type": "text/plain; charset=utf-8",
            },
        });
    }
});
