import { MetadataRoute } from 'next';

// All AI glossary terms
const allTerms = [
  { slug: "algorithm" },
  { slug: "artificial-general-intelligence" },
  { slug: "artificial-intelligence" },
  { slug: "attention-mechanism" },
  { slug: "augmented-intelligence" },
  { slug: "autoencoder" },
  { slug: "backpropagation" },
  { slug: "bias" },
  { slug: "big-data" },
  { slug: "bot" },
  { slug: "chatbot" },
  { slug: "computer-vision" },
  { slug: "convolutional-neural-network" },
  { slug: "cost-function" },
  { slug: "data-augmentation" },
  { slug: "data-mining" },
  { slug: "deep-learning" },
  { slug: "diffusion-model" },
  { slug: "embedding" },
  { slug: "epoch" },
  { slug: "ethical-ai" },
  { slug: "expert-system" },
  { slug: "feature-engineering" },
  { slug: "feature-extraction" },
  { slug: "fine-tuning" },
  { slug: "foundation-model" },
  { slug: "generative-adversarial-network" },
  { slug: "generative-ai" },
  { slug: "gradient-descent" },
  { slug: "ground-truth" },
  { slug: "hallucination" },
  { slug: "hyperparameter" },
  { slug: "hybrid-ai" },
  { slug: "inference" },
  { slug: "intelligent-agent" },
  { slug: "interpretability" },
  { slug: "internet-of-things" },
  { slug: "joint-probability" },
  { slug: "json" },
  { slug: "k-means-clustering" },
  { slug: "knowledge-base" },
  { slug: "knowledge-graph" },
  { slug: "k-nearest-neighbors" },
  { slug: "large-language-model" },
  { slug: "learning-rate" },
  { slug: "linear-regression" },
  { slug: "logistic-regression" },
  { slug: "machine-learning" },
  { slug: "model" },
  { slug: "multimodal-ai" },
  { slug: "natural-language-generation" },
  { slug: "natural-language-processing" },
  { slug: "natural-language-understanding" },
  { slug: "neural-network" },
  { slug: "normalization" },
  { slug: "ocr" },
  { slug: "one-shot-learning" },
  { slug: "overfitting" },
  { slug: "parameter" },
  { slug: "pattern-recognition" },
  { slug: "prompt" },
  { slug: "prompt-engineering" },
  { slug: "preprocessing" },
  { slug: "pretrained-model" },
  { slug: "quantization" },
  { slug: "query" },
  { slug: "retrieval-augmented-generation" },
  { slug: "recurrent-neural-network" },
  { slug: "reinforcement-learning" },
  { slug: "resnet" },
  { slug: "robotics" },
  { slug: "semi-supervised-learning" },
  { slug: "sentiment-analysis" },
  { slug: "supervised-learning" },
  { slug: "support-vector-machine" },
  { slug: "synthetic-data" },
  { slug: "token" },
  { slug: "tokenization" },
  { slug: "transfer-learning" },
  { slug: "transformer" },
  { slug: "turing-test" },
  { slug: "underfitting" },
  { slug: "unsupervised-learning" },
  { slug: "validation-set" },
  { slug: "vector-database" },
  { slug: "virtual-assistant" },
  { slug: "vision-transformer" },
  { slug: "weak-ai" },
  { slug: "weight" },
  { slug: "weights-and-biases" },
  { slug: "explainable-ai" },
  { slug: "zero-shot-learning" }
];

const baseUrl = 'https://www.hirenest.ai';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: `${baseUrl}/ai-glossary`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    ...allTerms.map((term) => ({
      url: `${baseUrl}/ai-glossary/${term.slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
  ];
}
