/**
 * Unique interview questions for each job to replace template content.
 * These questions are completely different for each role - no repetition across jobs.
 */

export const uniqueJobQuestions: Record<string, {
  common: Array<{ id: string; question: string; answer: string }>;
  technical: Array<{ id: string; question: string; answer: string }>;
  companyFit: Array<{ id: string; question: string; answer: string }>;
  situational: Array<{ id: string; question: string; answer: string }>;
}> = {
  // Product Manager
  'product-manager': {
    common: [
      { id: "pm-favorite-product", question: "Tell me about a product you love and how you'd improve it.", answer: "Choose a product you actually use and can analyze deeply. I'm a heavy Notion user. What I love is the flexibility—databases, docs, and wikis in one place. But I think the mobile experience is weak compared to desktop—the complex databases are hard to use on small screens. I'd improve this by creating a simplified mobile view for databases, with progressive disclosure of complexity. I'd also add better offline functionality since I often find myself wanting to access docs without connectivity. The opportunity is making power features accessible without overwhelming casual users." },
      { id: "pm-feature-tradeoff", question: "Describe a time you had to say no to a stakeholder request.", answer: "Show diplomatic prioritization. A sales leader insisted on a feature for their largest prospect. I investigated and found this prospect represented 2% of our TAM but the feature would take 3 months to build. I met with the sales leader, acknowledged the opportunity, but walked through the trade-offs: building this would delay three other features that would benefit 80% of customers. We compromised: created a manual workaround for this prospect while prioritizing one of the other features that would also help this customer segment. The prospect appreciated the responsiveness, and we shipped the broader feature a month later." },
      { id: "pm-data-decision", question: "Tell me about a time data contradicted your intuition.", answer: "Show data-driven thinking. I believed our users wanted advanced analytics because power users requested it constantly. But when we surveyed and interviewed our broader user base, we found 70% were confused by our current basic analytics—they wanted simplicity, not more features. The data was clear: power users were vocal but small. We pivoted to simplify the existing analytics instead of building advanced features. Adoption increased 40% and our NPS on analytics went from negative to positive. It taught me that the loudest users aren't always representative." },
      { id: "pm-launch-failure", question: "Tell me about a product launch that didn't go as planned.", answer: "Be honest about learning. We launched a feature I'd spent months on, and usage was disappointing. We'd built what we thought was perfect, but users weren't adopting it. I did user interviews and discovered we'd solved the wrong problem—users had a workaround that was good enough. I felt terrible, but I learned to talk to users earlier in the process. We eventually pivoted the feature to address the real pain point, and second launch was much more successful. Now I do user discovery before writing a single spec—it's uncomfortable but saves everyone time." },
      { id: "pm-stakeholder-conflict", question: "How do you handle disagreement between engineering and design?", answer: "Show facilitation skills. I had a situation where engineering wanted to build a scalable, reusable solution while design wanted a quick, custom implementation that better served user needs. Both perspectives were valid. I brought them together and we identified the core tension: long-term technical health vs short-term user experience. We compromised: built the custom solution for launch but allocated tech debt work to make it reusable later. The key was making the trade-off explicit and getting both sides to agree it was the right call for the business." },
      { id: "pm-influence-without-authority", question: "How do you get alignment when you don't have direct authority?", answer: "Show influence skills. I rely on building strong relationships and making my reasoning transparent. Before presenting to a group, I meet with key stakeholders individually to understand their concerns and incorporate their feedback. When we discuss as a group, I've already built consensus on the problem and constraints, so we're debating solutions rather than starting from scratch. I also come with data—user research, analytics, competitive analysis—which helps align us on facts rather than opinions. People support what they help create, so I focus on collaborative development." }
    ],
    technical: [
      { id: "pm-metrics-framework", question: "What metrics would you track for a new B2B SaaS product?", answer: "Show full-funnel thinking. I'd track acquisition metrics (website visits, sign-ups), activation metrics (time to first value, feature adoption in first 7 days), engagement metrics (DAU/WAU, session frequency, core feature usage), retention metrics (cohort retention, churn rate), and monetization metrics (free-to-paid conversion, ARPU, LTV:CAC). The key is linking metrics to the business model—for B2B SaaS, retention and expansion revenue are critical. I'd also track leading indicators that predict retention, like feature adoption patterns and user engagement scores." },
      { id: "pm-ab-test", question: "How would you design an A/B test for a pricing change?", answer: "Show experimental rigor. First, I'd clarify the hypothesis: what change are we making and what do we expect to happen? Then I'd design the test: random assignment (by user or account), control vs variant, primary metric (conversion rate) and guardrail metrics (churn, support calls). I'd calculate sample size needed for statistical power given our baseline conversion and minimum detectable effect. For pricing, I'd run it longer to observe behavioral changes over time. Most importantly, I'd analyze not just the average treatment effect, but heterogeneity—does it work differently for different customer segments?" },
      { id: "pm-tech-stack-opinion", question: "How technical should a PM be? What's your approach?", answer: "Show balanced perspective. I don't think PMs need to be engineers, but I believe technical fluency is increasingly important. I can't write production code, but I can read and understand code, participate in architecture discussions at a conceptual level, and push back on unrealistic estimates. I think the right level is: understand technical constraints, ask good questions, and build trust with engineering by demonstrating I respect their craft. I also believe in being honest about what I don't know—asking help me understand why this is hard builds more credibility than pretending to know." },
      { id: "pm-api-design", question: "How do you approach API design for a developer product?", answer: "Show domain knowledge. For developer products, the API is the product. I'd start by understanding developer workflows: what are they trying to accomplish, what are their pain points with existing solutions? For API design specifically, I'd prioritize simplicity and consistency—intuitive naming, clear error messages, and comprehensive documentation. I'd also think about the developer experience: SDKs in popular languages, code examples, and good error handling. I'd test the API with real developers before launch, observing where they struggle. Great APIs are opinionated but flexible, and documentation is as important as the API itself." },
      { id: "pm-data-infrastructure", question: "What data infrastructure would you want in place?", answer: "Show practical needs. I'd want event tracking from day one: every meaningful user action instrumented with consistent event properties. I'd use a tool like Mixpanel or Amplitude for product analytics, with a data warehouse (Snowflake/BigQuery) for custom analysis. For experimentation, I'd want a platform like Optimizely or Statsig for running A/B tests with proper statistical guardrails. For dashboards, I'd set up Looker or Mode for team visibility. Critically, I'd want a data catalog documenting what each event means and how it's tracked—otherwise, analytics becomes chaos as the product grows." }
    ],
    companyFit: [
      { id: "pm-why-this-company", question: "What product problem do you think we should solve?", answer: "Research beforehand. Based on my research, I noticed you're strong in [market] but I see an opportunity in [adjacent area]. Your core users have mentioned [need] in reviews and forums, and while your competitors are moving there, I haven't seen you address it yet. I think there's a first-mover opportunity if you move fast. Of course, I'd want to validate this hypothesis with user research before committing significant resources, but it seems like a natural extension of your current product that could open up a new market segment." },
      { id: "pm-working-style", question: "How do you like to work with engineering and design?", answer: "Show collaborative mindset. I believe the best products come from tight collaboration. With engineering, I like to involve them early in the ideation phase—they often spot constraints or opportunities I miss. I try to write clear specs but stay open to their ideas on implementation. With design, I like to co-create—understanding user research together and iterating on solutions together. I see product, design, and engineering as a triad: we each bring different perspectives and all need to be aligned for success. Regular check-ins and being available for questions beats formal processes." },
      { id: "pm-career-goals", question: "What does success look like for you as a PM here?", answer: "Show alignment. Success would be shipping products that customers love and that move the business metrics. Specifically, I'd want to see the features I own driving engagement and revenue growth. I'd also want to earn trust with my cross-functional partners—the engineers I work with should feel I represent them well to the business, and the business should feel I'm delivering value. Long-term, I'd hope to grow into larger scope—either managing a product area or moving into a group PM role. I want to be somewhere I can deepen my skills while taking on more responsibility over time." }
    ],
    situational: [
      { id: "pm-engineering-cut", question: "Engineering cut your roadmap by 50%. What do you do?", answer: "Show prioritization skills. First, I'd clarify what's fixed (must-haves) versus flexible. Then I'd ruthlessly prioritize using a framework like RICE: what features have the highest Reach, Impact, Confidence, and lowest Effort? I'd focus on protecting things that drive near-term revenue or critical user needs. I'd communicate with stakeholders about what's being cut and why, offering to revisit when resources free up. The goal is maximizing impact under constraints, not protecting my original plan. Sometimes constraints lead to better, more focused products." },
      { id: "pm-founder-disagrees", question: "The founder insists on a feature you think is a bad idea. What do you do?", answer: "Show diplomacy. I wouldn't immediately say no—I'd seek to understand their thinking. What problem are they trying to solve? What user feedback or market observation is driving this? Sometimes founders see things I don't. But I'd also present my perspective: share relevant data, walk through the trade-offs, and perhaps propose a small experiment to test their hypothesis. If they're adamant after that, I'd execute well while documenting my concerns. Sometimes you have to disagree and commit—but I'd make sure we're measuring closely so we can learn quickly if I was right." },
      { id: "pm-competitor-launch", question: "A competitor just launched a feature we were planning. What do you do?", answer: "Show strategic thinking. First, I'd understand what they actually shipped versus what we were planning—surface-level similarity doesn't mean same value. I'd analyze their approach, identify what they did well and what gaps remain. Sometimes following a competitor's move isn't strategic—we can differentiate elsewhere. Other times, being first-mover isn't an advantage and we can learn from their execution. If we still believe the feature is valuable, I'd look at how to ship it differently or better. The key is making an intentional choice, not reacting out of FOMO." }
    ]
  }
};

// Helper to get unique questions for a job
export function getUniqueQuestionsForJob(slug: string) {
  return uniqueJobQuestions[slug];
}

// Helper to check if job has unique questions
export function hasUniqueQuestions(slug: string): boolean {
  return slug in uniqueJobQuestions;
}
