// scripts/test-internal-links.ts
/**
 * Test all internal links generated by the SEO helper functions
 * Verifies that all internal links point to valid pages
 */

import { enabledJobTitles } from '../app/lib/programmatic-seo/enabled-job-titles'
import { getRelatedPages, getCrossTemplateLinks } from '../app/lib/seo/helpers'

const BASE_URL = 'https://hirenest.ai'
const testedUrls = new Set<string>()
const failedUrls: Array<{ url: string; reason: string }> = []

console.log(`Testing internal links for ${enabledJobTitles.length} job titles...\n`)

// Track stats
let totalRelatedLinks = 0
let totalCrossTemplateLinks = 0
let uniqueValidLinks = 0

// Test all internal links from helper functions
for (const job of enabledJobTitles) {
  const templates = ['interview-questions', 'resume-keywords', 'salary', 'cover-letter', 'job-description'] as const

  for (const template of templates) {
    // Test getRelatedPages
    const relatedPages = getRelatedPages(job.slug, template, 6)
    totalRelatedLinks += relatedPages.length

    // Test getCrossTemplateLinks
    const crossTemplateLinks = getCrossTemplateLinks(job.slug, job.title)
    totalCrossTemplateLinks += crossTemplateLinks.length

    for (const page of [...relatedPages, ...crossTemplateLinks]) {
      const url = page.url

      // Skip already tested URLs
      if (testedUrls.has(url)) continue
      testedUrls.add(url)
      uniqueValidLinks++

      // Validate URL format
      if (!url.startsWith(BASE_URL)) {
        console.log(`❌ Invalid URL format: ${url}`)
        failedUrls.push({ url, reason: 'Invalid base URL' })
        continue
      }

      // Extract and validate slug
      const urlParts = url.split('/')
      const slug = urlParts[urlParts.length - 1]

      if (!slug) {
        console.log(`❌ Missing slug: ${url}`)
        failedUrls.push({ url, reason: 'Missing slug' })
        continue
      }

      // Verify slug exists in enabledJobTitles (for programmatic pages)
      // Skip verification for main pages like /interview-questions, /salary, etc.
      if (urlParts.includes('interview-questions') && slug !== 'interview-questions' &&
          urlParts.includes('resume-keywords') && slug !== 'resume-keywords' &&
          urlParts.includes('salary') && slug !== 'salary' &&
          urlParts.includes('cover-letter') && slug !== 'cover-letter' &&
          urlParts.includes('job-description') && slug !== 'job-description') {

        const jobExists = enabledJobTitles.find(j => j.slug === slug)
        if (!jobExists) {
          console.log(`❌ Slug not found in enabledJobTitles: ${slug}`)
          failedUrls.push({ url, reason: `Slug "${slug}" not found in enabledJobTitles` })
        }
      }
    }
  }
}

// Print summary
console.log(`\n${'='.repeat(50)}`)
console.log(`INTERNAL LINK TEST RESULTS`)
console.log(`${'='.repeat(50)}`)
console.log(`Total job titles tested: ${enabledJobTitles.length}`)
console.log(`Total related links generated: ${totalRelatedLinks}`)
console.log(`Total cross-template links generated: ${totalCrossTemplateLinks}`)
console.log(`Unique valid internal links: ${uniqueValidLinks}`)
console.log(`${'='.repeat(50)}`)

if (failedUrls.length > 0) {
  console.log(`\n⚠️  Found ${failedUrls.length} problematic links:\n`)

  // Group by reason
  const byReason: Record<string, string[]> = {}
  for (const fail of failedUrls) {
    if (!byReason[fail.reason]) byReason[fail.reason] = []
    byReason[fail.reason].push(fail.url)
  }

  for (const [reason, urls] of Object.entries(byReason)) {
    console.log(`\n${reason} (${urls.length} URLs):`)
    urls.slice(0, 10).forEach(url => console.log(`  - ${url}`))
    if (urls.length > 10) {
      console.log(`  ... and ${urls.length - 10} more`)
    }
  }

  console.log(`\n❌ Internal link validation failed!`)
  process.exit(1)
} else {
  console.log(`\n✅ All internal links validated successfully!`)
  console.log(`   All ${uniqueValidLinks} unique internal links point to valid pages.`)
}
