import { ConvexHttpClient } from "convex/browser";
import { api } from "@/convex/_generated/api";

export const dynamic = "force-dynamic";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://hirenest.ai";
const SITE_NAME = "Hirenest AI";

function getClient(): ConvexHttpClient {
    const url = process.env.NEXT_PUBLIC_CONVEX_URL;
    if (!url) throw new Error("NEXT_PUBLIC_CONVEX_URL is not set");
    return new ConvexHttpClient(url);
}

export async function GET() {
    const client = getClient();

    // Fetch all published posts via cursor pagination
    let cursor: string | null = null;
    let allPosts: { title: string; description: string; slug: string; date: string }[] = [];
    let isDone = false;

    while (!isDone) {
        const result: {
            posts: { title: string; description: string; slug: string; date: string; published: boolean; unlisted: boolean }[];
            continueCursor: string;
            isDone: boolean;
        } = await client.query(api.posts.getRSSPostsBatch, {
            cursor,
            numItems: 100,
            includeContent: false,
        });
        const filtered = result.posts.filter(
            (p) => p.published && !p.unlisted
        );
        allPosts.push(...filtered);
        cursor = result.continueCursor;
        isDone = result.isDone;
        if (allPosts.length > 5000) break;
    }

    // Sort by date descending
    allPosts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    let availableContent = "";
    if (allPosts.length > 0) {
        availableContent = "\n## Available Content\n\n";
        for (const post of allPosts) {
            availableContent += `### [${post.title}](${SITE_URL}/blog/${post.slug})\n`;
            availableContent += `- **Type**: Post\n`;
            availableContent += `- **Date**: ${post.date}\n`;
            availableContent += `- **Markdown URL**: ${SITE_URL}/raw/${post.slug}.md\n`;
            if (post.description) {
                availableContent += `- **Description**: ${post.description}\n`;
            }
            availableContent += "\n";
        }
    }

    const content = `# ${SITE_NAME}

This file provides LLM-friendly access to the content on this website.

---
- **Site URL**: ${SITE_URL}
- **Format**: Append \`?llm=1\` to any post/page URL to get markdown
---
${availableContent}
---
*Generated by [LLM Ready](https://hirenest.ai) - Make your content AI-ready*
`;

    return new Response(content, {
        headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, max-age=3600, s-maxage=7200",
        },
    });
}